# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c78c9776086c08f1c92caaf54f2cee40b57a8a99c022168781ec917a6936881bffac1105824debdb6eebdff5311db1626e2633b3389ac6e77632aec25309f74

test:
  secret_key_base: 5e59d8acb2ec92b7b1bc98179d01feb5a8952e580f35b0c48a68ad86a5d0928a61d8ee0e66237040ebb33ff2503eaa2a35ee8b95409d030132a496d6ce449095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
